### ISSUE TITLE
Allow comparing network configs with different network topologies

### ISSUE THREAD

**Issue by shai-doron** [IBM/network-config-analyzer#1]
Today, we can only compare (check for containment, equality, ...) two NetworkConfig objects with equal PeerContainers. i.e., the two configs must have exactly the same set of peers (with the same labels) and the peers must be partitioned in the same way into namespaces. The only difference we allow is in the set of NetworkPolicies.

However, the network config changes not only when NetworkPolicy objects change, but also when peers are added/deleted/modified. Users would like to be notified of the effects of such changes. For example, when I change a Pod's label, which connections are now allowed/denied.

Some of the changes will be very hard to reason about. If we rename a pod or move it to another namespace, correlating the "old" set of peers to the "new" set of peers becomes a guessing work. Hence, we assume peers are correlated using their (fully qualified) name.

The proposed solution is to provide the user with a report divided into 5 sections:

**a)**

> - lost connections between removed peers (east-west connections)
> - lost connections between removed peers and {old ipBlocks + unreferenced ipBlocks} (old ipBlocks = removed ipBlocks + intersected ipBlocks)
> 

**b)**

> - lost connections between removed peers and intersected peers (east-west connections)

**c)**

> - lost/new connections between intersected peers due to changes in policies and labels of pods/namespaces (east-west connections)
> **north-south connections:**
> - lost connections between intersected peers and removed ipBlocks 
> - lost/new connections between intersected peers and intersected {ipBlocks + unreferenced ipBlocks} (due to changes in policies and labels of pods/namespaces)
> - new connections between intersected peers and new ipBlocks

**d)**

> - new connections between intersected peers and added peers (east-west connections)

**e)**

> - new connections between added peers (east-west connections)
> - new connections between added peers and {new ipBlocks + unreferenced ipBlocks} (new ipBlocks = intersected ipBlocks + added ipBlocks + unreferenced ipBlocks) (north-south connections)

Some of the section might be empty and can be dropped.

![semanticDiff1](https://user-images.githubusercontent.com/53252291/117951885-47811f00-b31d-11eb-83eb-d940b65d574d.GIF)

![semanticDiff2](https://user-images.githubusercontent.com/53252291/119509298-30a8e680-bd79-11eb-8edf-17ce62722d91.GIF)

---
**Work items**
- [x] Bring over SemanticDiff query for identical topologies from CRA branch
- [x] Enhance SemanticDiff query to support nonidentical topologies
- [x] Containment and twoWayContainment queries - support nonidentical topologies
