### ISSUE TITLE
Tighter syntax checking and type checking for policies

### ISSUE THREAD

**Issue by shai-doron** [IBM/network-config-analyzer#4]
[NCA_networkPolicyParserChecksAndTests.docx](https://github.com/IBM/network-config-analyzer/files/6392825/NCA_networkPolicyParserChecksAndTests.docx)
In the shift-left scenario we may no longer have k8s checking syntax and type safety for us.
Policy yaml parsers should be therefore more strict.

----------------
**Work items**

- [x] Review specifications of k8s NetworkPolicy https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#networkpolicy-v1-networking-k8s-io
- [x] Define a set of fields that need to be checked (the fields that are not auto generated) - see attachment
- [x] Add unit testing that checks good-path of all fields that are defined to be checked above
- [x] Test on live k8s cluster and adjust checkers as needed
- [x] Run full regression testing and fix failing unit tests as required
- [x] Implement bad-path testing
- [ ] Enhance to check Calico policies

**Comment by shai-doron** [comment]
@shireenf-ibm, Ziv suggested to enhance function `check_keys_are_legal` by passing an optional type (as an input argument to the function) to check that the key complies with. Let's consider this.

**Comment by zivnevo** [comment]
Possibly `check_keys_are_legal` can also check allowed values whenever applicable (e.g., for `protocol` or for `policyTypes`)

**Comment by shireenf-ibm** [comment]
> 
> 
> @shireenf-ibm, Ziv suggested to enhance function `check_keys_are_legal` by passing an optional type (as an input argument to the function) to check that the key complies with. Let's consider this.

since we call the "check_keys_are_legal" only for dictionaries, I added a type check for dict whenever it exists (not None/empty) in the function (no need for a new parameter)

**Comment by shireenf-ibm** [comment]
[NCA_k8s_networkPolicy_parser_tests.xlsx](https://github.com/IBM/network-config-analyzer/files/6516022/NCA_k8s_networkPolicy_parser_tests.xlsx)

**Comment by shireenf-ibm** [comment]
[NCA_k8s_networkPolicy_parser_tests.xlsx](https://github.com/IBM/network-config-analyzer/files/6528936/NCA_k8s_networkPolicy_parser_tests.xlsx)

**Comment by zivnevo** [comment]
Will not implement for Calico
